# pylint: disable=line-too-long
from srl_model.modules.span_extractors.span_extractor import SpanExtractor
from srl_model.modules.span_extractors.endpoint_span_extractor import EndpointSpanExtractor
from srl_model.modules.span_extractors.self_attentive_span_extractor import SelfAttentiveSpanExtractor
from srl_model.modules.span_extractors.bidirectional_endpoint_span_extractor import BidirectionalEndpointSpanExtractor
