from srl_model.modules.attention.attention import Attention
from srl_model.modules.attention.bilinear_attention import BilinearAttention
from srl_model.modules.attention.cosine_attention import CosineAttention
from srl_model.modules.attention.dot_product_attention import DotProductAttention
from srl_model.modules.attention.legacy_attention import LegacyAttention
from srl_model.modules.attention.linear_attention import LinearAttention
